# Experiment ranges
start: 0
end: 30
nst_range: [1, 3, 5]

# Learning parameters
gamma: 0.9
learning_rate: 0.1
epsilon_initial: 1.0
epsilon_decay: 0.997
epsilon_min: 0.01
max_steps: 49
N_steps: 20000
test_steps: 4

# Transition configuration
x_percentage: 0
bound_update_freq: 5000
