import os

base_path = r"C:\Users\kevin\OneDrive\Desktop\TMLR 2025\Exp 6 Noise\autogenerated"

# Iterate through folders 0 to 30
for i in range(30):
    folder_path = os.path.join(base_path, str(i))

    if not os.path.isdir(folder_path):
        print(f"Skipping {folder_path} (not a directory)")
        continue

    for filename in os.listdir(folder_path):
        full_path = os.path.join(folder_path, filename)

        # Check if it's a file, not the excluded one, and starts with char < 't'
        if (
            os.path.isfile(full_path)
            and filename.lower() != "mdp_exp_01.txt"
            and filename[0].lower() < 't'
        ):
            try:
                os.remove(full_path)
                print(f"Deleted: {full_path}")
            except Exception as e:
                print(f"Failed to delete {full_path}: {e}")
