start: 0
end: 30
nst_range: [1, 2, 4]
gamma: 0.9
x_percentage: 0

# Q-learning parameters
learning_rate: 0.1
epsilon_initial: 1.0
epsilon_decay: 0.9998
epsilon_min: 0.01
max_steps: 20
N_steps: 24000
test_steps: 8
